# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# | 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# | 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# + -------------------------------------------------------------------------------- + #
messages:
  # (메시지 앞에 붙는) 접두사
  prefix: ' &6 가구 | &r'

  # 콘피그를 리로드 하였을 때 출력되는 메시지
  reloadComplete: '&a콘피그를 리로드 하였습니다.'

  # 가구를 생성 하였을 때 출력되는 메세지
  createFurniture: '{name} 가구를 생성 하였습니다.'

  # 가구를 삭제 하였을 때 출력되는 메세지
  removeFurniture: '{name} 가구를 삭제 하였습니다.'

  # 가구 메뉴를 오픈하였을 때 출력되는 메세지
  openFurnitureMenu: '가구 메뉴를 열었습니다.'

  # 가구를 설치 하였을 때 출력되는 메세지
  onPlaceFurniture: '{name} 가구를 설치 하였습니다.'

  # 가구를 제거/회수 하였을 때 출력되는 메세지
  onRemoveFurniture: '{name} 가구를 제거 하였습니다.'

errorMessages:
  # 권한이 없을 때 출력되는 메시지
  noPermission: '&c해당 명령어를 실행할 권한이 없습니다.'

  # 잘못된 명령어를 사용하였을 때 출력되는 메시지
  wrongCommand: '&c잘못된 명령어입니다. (다시 시도해주세요)'

  # 콘솔에서 사용하지 못하는 명령어를 사용하였을 때 출력되는 메시지
  noConsoleCommand: '&c콘솔에서는 사용할 수 없는 명령어입니다.'

  # 이미 존재한 이름을 입력하였을때 출력되는 메세지
  alreadyExistName: '&c이미 존재하는 이름입니다.'

  # 인벤토리에 공간이 없을때 출력되는 메세지
  noSpaceInInventory: '&c인벤토리에 공간이 없습니다.'

  # 가구 목록이 비어있을때 출력되는 메세지
  noItemInMenu: '&c가구 목록이 비어있습니다.'