name: ST-Furniture
main: net.starly.furniture.Furniture
author: Starly Team
website: http://starly.kr/

description: Furniture Plugin.

depend: [ ST-Core ]
version: 1.0
api-version: 1.13

commands:
  furniture:
    aliases: [ 가구 ]